[package]
name = "tuono_lib_macros"
version = "0.8.1"
edition = "2021"
description = "The react/rust fullstack framework"
keywords = [ "react", "typescript", "fullstack", "web", "ssr"]
repository = "https://github.com/Valerioageno/tuono"
readme = "../../README.md"
license-file = "../../LICENSE.md"
categories = ["web-programming"]
include = [
		"src/*.rs",
		"Cargo.toml"
]

[lib]
crate_type = ["proc-macro"]
proc-marco = true

[dependencies]
syn = { version = "1.0.59", features = ["full"] }
quote = "1.0"
